version: '3.8'

services:
  app:
    build:
    command: npm run dev
    env_file: .env.local
    ports:
      - '8000:8000'
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    ports:
      - '6379:6379'

volumes:
  mongo_data:
