services:
  app:
    build: .
    command: npm run dev
    ports:
      - '8000:8000'
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/attend
      - REDIS_URL=redis://redis:6379
      - EMAIL_USER=haywhy2946@gmail.com
      - EMAIL_PASS=qswjiqjeloexybwr
      - JWT_SECRET=dev_secret_key
      - ADMIN_EMAILS=haywhy2946@gmail.com,ayowolesodipe@gmail.com
      - APP_URL=http://localhost:8000

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    ports:
      - '6379:6379'

volumes:
  mongo_data:
